# This workflow will run MyPy static typing analysis.

name: mypy testing

on: [push, pull_request]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
      - name: Run Mypy tests
        run: |
          mypy --config-file=mypy.ini fffw
